name: CI

on:
    pull_request:
        branches: ['2.x', '2.x-stable']
    push:
        branches: ['2.x', '2.x-stable']

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                distribution: 'temurin'
                java-version: '8'
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
              with:
                build-root-directory: ./packages/clay-isomorphic
                gradle-version: 6.6.1
                arguments: build
            - uses: actions/setup-node@v2
              with:
                node-version: '10'
            - uses: actions/cache@v2
              with:
                path: '**/node_modules'
                key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies
              run: yarn install
            - name: Make gradlew executable
              run: chmod +x ./packages/clay-isomorphic/gradlew
            - name: Test Soy
              run: yarn testSoy
            - name: Lint
              run: yarn lint
            - name: Format
              run: yarn checkFormat
            - name: Soy Build
              run: yarn soy
            - name: Run Jest
              env:
                  CI: true
              run: yarn jest
